[package]
name = "leetcode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "lib.rs"

[dependencies]
regex = "1.10.5"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "=1.0.1"
